### ISSUE TITLE
[Adicionar Palestrante] Kirill Cherkashin

### ISSUE THREAD

**Issue by Lucasktrindade** [gdgrio/devfest#41]
## O quê precisa ser feito?

- Adicionar informações sobre o palestrante no ```data/speaker.yml```
- Adicionar informações da palestra no  ```data/sessions.yml``` e ligar ao id do speaker criado, a imagem do palestrante deve ficar em ```img/people```.

## Informações para serem adicionadas

- Info do Palestrante
   - Nome: Kirill Cherkashin
   - Bio: Kirill Cherkashin, originally from Moscow, now lives in NYC working for Firebase. He enjoys teaching and organising meetups. He has been teaching Web for the past few years, and is the organiser for AngularNYC, ReactNYC and soon VueNYC! He loves Angular and teaches it at Google and all over the world. In spare time, He enjoys dancing tango, reading books and good conversations.
   - Empresa: Google Firebase
   - Cargo: Developer
   - Foto: 
![unnamed](https://user-images.githubusercontent.com/13908465/47062239-56c27f00-d1ab-11e8-9659-fc332c55d33e.jpg)

- Info da Palestra
  - Título: JAVASCRIPT ❤️ BINARY DATA
  - Descrição: In this talk we’ll go pretty low level!
We’ll explore the tools JavaScript has to offer for working with binary data, see how the popular binary formats are structured and how Serialized Frameworks like Thrift/protobuf use binary for speed and efficiency. 
  - Complexidade: Intermediário

**Comment by alfa-dev** [comment]
Estou pegando essa issue.
