### ISSUE TITLE
[Palestra] Syncing (UX) Design sprints 

### ISSUE THREAD

**Issue by Lucasktrindade** [gdgrio/devfest#42]
## O quê precisa ser feito?

- Adicionar palestra do Michael Dorka, na parte de ```data/sessions.yml```

## Informações sobre a palestra

- Info da palestra
   - Nome: Syncing (UX) Design sprints 
   - Descrição: In this talk I want to share with you some experiences about the importance of design sprints and why and how you can sync between Design/Research, Product and Development teams. 
  - Complexidade: Intermediário

**Comment by alfa-dev** [comment]
Estou pegando essa issue.
