### ISSUE TITLE
Adicionar Palestrante e Palestra Lucila De Pasquale

### ISSUE THREAD

**Issue by Lucasktrindade** [gdgrio/devfest#45]
## Palestrante
Name: Lucila De Pasquale
Company: Google
Title: Product Designer
Bio: Lucila De Pasquale is a Product Designer at Google, where she designing and builds new digital products for emerging markets. 
She has an extensive educational background and working experience in design in Europe, South America, North America, the Caribbean and Asia.
Before joining Google, she was the head of UX at Taiger, an artificial intelligence company, and later worked for ThoughtWorks as the User Experience lead for Asia Pacific. She has a deep understanding of the intersection between human psychology and technology, to help solve complex business challenges.
Foto: 
![4803afc4-71fb-4e95-8409-6ca127126dee](https://user-images.githubusercontent.com/13908465/47441960-cc1fe800-d787-11e8-8fbf-3e8809606727.jpg)

## Palestra
Title: Google's Next Billion Users
Description: Millions of new internet users will be coming online in the near future, but many will still have slow and intermittent access. Learn best practices about designing products and experiences for constrained connectivity contexts, and about what Google's new initiatives to build for the Next Billion users
Complexity: Iniciante

**Comment by alfa-dev** [comment]
Estou com essa issue.
